/**
 * Custom Cloudflare Worker entrypoint.
 *
 * Wraps OpenNext's generated handler so the same Worker can serve HTTP
 * (`fetch`, delegated untouched to OpenNext) AND run a Cron Trigger
 * (`scheduled`). `wrangler.jsonc` points `main` here; `pnpm cf:build` still
 * emits `.open-next/worker.js`, which we import and re-export below.
 *
 * The scheduled handler does NOT touch the database directly — it dispatches
 * an internal request to `/api/cron/hubspot` through OpenNext's own `fetch`.
 * That keeps all app code (DB driver, dynamic requires, Cloudflare context
 * wiring) inside the OpenNext bundle, where production already handles it,
 * instead of re-bundling `@/lib` into this thin shim.
 *
 * This file is excluded from `tsc` (see tsconfig) because `.open-next/worker.js`
 * doesn't exist until `cf:build` runs; wrangler bundles it with esbuild at
 * deploy time.
 */
// @ts-expect-error generated by `opennextjs-cloudflare build`; absent until then.
import { default as openNextHandler } from "./.open-next/worker.js";

type Env = { CRON_SECRET?: string };
type Ctx = { waitUntil(p: Promise<unknown>): void; passThroughOnException(): void };

export default {
  fetch: openNextHandler.fetch,

  async scheduled(_event: unknown, env: Env, ctx: Ctx): Promise<void> {
    const run = async () => {
      const req = new Request("https://cron.internal/api/cron/hubspot", {
        method: "POST",
        headers: { "x-cron-secret": env.CRON_SECRET ?? "" },
      });
      const res: Response = await openNextHandler.fetch(req, env, ctx);
      if (!res.ok) {
        console.error("[cron] /api/cron/hubspot returned", res.status, await res.text());
      }
    };
    ctx.waitUntil(
      run().catch((err) => {
        console.error("[cron] scheduled handler failed:", err);
      }),
    );
  },
};
